apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    isDefault: true
    jsonData:
      version: Flux
      organization: jmeter-org-Influx
      defaultBucket: jmeter_data
    secureJsonData:
      token: 5rX2uEJgCoEhIYU0C71aWY8XEJpu8J38LQUA2GKg43evoSEFF2vUup3ite0K_vCxb9p2GobGIxeaknJPIo5ssQ==
    url: http://172.28.100.2:8086
